<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SolidWorksCadAgent.RemoteAgent</RootNamespace>
    <AssemblyName>SolidWorksCadAgent.RemoteAgent</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Security" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <ProjectReference Include="..\SolidWorksCadAgent.Core\SolidWorksCadAgent.Core.csproj" />
  </ItemGroup>
</Project>
